version: '3.9'

services:
  redis:
    image: redis
    restart: always

  rabbit:
    hostname: rabbit
    restart: always
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"

  backend:
    build:
      context: ./backend
    command: python /usr/src/app/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/app/
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=alitics-admin
      - POSTGRES_PASSWORD=alitics-admin
      - POSTGRES_DB=functions

  worker:
    restart: always
    build:
      context: ./backend
    volumes:
      - ./backend/:/usr/src/app/
    command: ['celery', '-A', 'backend', 'worker']
    depends_on:
      - rabbit
      - redis

volumes:
  postgres_volume: