# Generated by Django 3.2.6 on 2021-08-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='graph',
            field=models.ImageField(blank=True, upload_to='', verbose_name='График'),
        ),
    ]
