# Generated by Django 3.2.6 on 2021-08-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0002_alter_function_graph'),
    ]

    operations = [
        migrations.RenameField(
            model_name='function',
            old_name='function',
            new_name='string_view',
        ),
        migrations.AlterField(
            model_name='function',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата  обработки'),
        ),
    ]
