# Generated by Django 3.2.6 on 2021-08-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0004_function_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='graph',
            field=models.ImageField(blank=True, upload_to='graphs', verbose_name='График'),
        ),
        migrations.AlterField(
            model_name='function',
            name='update_date',
            field=models.DateTimeField(blank=True, verbose_name='Дата  обработки'),
        ),
    ]
