# Generated by Django 3.2.6 on 2021-08-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0005_auto_20210817_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата  обработки'),
        ),
    ]
